[R2]
account_id = "ce429aaa1e4d100ca6fa5adc85a40c00"
bucket = "bretagne-visibility-data"
access_key_id = "4dca79b3eb4d1e18f6ad3c30932d33cf"
secret_access_key = "173bd977a4a1f82f7a8ea5c2f854350394d0362cbe869ad72f880c572c6765f9"
region = "auto"
endpoint_url = "https://ce429aaa1e4d100ca6fa5adc85a40c00.r2.cloudflarestorage.com"
dataset_key = "datasets/dataset_visibility_app.parquet"

LOCAL_DATASET_PATH = "data/processed/ml/dataset_visibility_mvp_ml_ready_2024_2026.parquet"